113 transaction hash during signin
onlydustxyz/marketplace-frontend pull request #154
Opened 2022-10-09 13:43 UTC by J4ckyLIM

2022-10-09 19:29 UTC, ltoussaint requested changes
Hello @J4ckyLIM 

The task definition is not up to date.
The process does not involve a transaction anymore, so there is no need to display a transaction hash which does not exist.

What is needed :
- display a good message while the user is signing the message (which is part of the verification process that the account is yours). So when the signin window from ArgentX or Braavos appears, we should display a modal like "We need you to sign a message using your wallet to ensure your are the real owner. Then we will be able to link your Github account with your Starknet account."
- The second step include the call to our api to perform the connection between those 2 accounts. At this point you need to use the `toastPromise` method to manage ongoing, success and error messages.

2022-10-09 19:29 UTC, ltoussaint commented on src/App/Routes/Modals/RegisterModal/GithubSignin/index.tsx
> +      setTxHash(hash);
The `hash` variable is not a transaction hash but a simple hash of the message (which is a string) we want to sign. It's used by our backend to verify the signature.

2022-10-09 19:29 UTC, ltoussaint commented on src/App/Routes/Modals/RegisterModal/GithubSignin/View.tsx
> +          {txHash && (
You don't need this as there is no transaction ongiong.
Just change the message and close the modal when the user signed (or reject) the message

2022-10-09 20:36 UTC, J4ckyLIM commented
> Hello @J4ckyLIM
> 
> The task definition is not up to date. The process does not involve a transaction anymore, so there is no need to display a transaction hash which does not exist.
> 
> What is needed :
> 
> * display a good message while the user is signing the message (which is part of the verification process that the account is yours). So when the signin window from ArgentX or Braavos appears, we should display a modal like "We need you to sign a message using your wallet to ensure your are the real owner. Then we will be able to link your Github account with your Starknet account."
> * The second step include the call to our api to perform the connection between those 2 accounts. At this point you need to use the `toastPromise` method to manage ongoing, success and error messages.

- I see, but we're currently displaying a modal that displays the status of the of the process, does it mean we show an another modal before displaying the "process" modal ? 
- What call should be done to perform the connection between the 2 accounts ?

2022-10-10 10:01 UTC, ltoussaint commented
> * I see, but we're currently displaying a modal that displays the status of the of the process, does it mean we show an another modal before displaying the "process" modal ?
> * What call should be done to perform the connection between the 2 accounts ?

- No, the current modal must stay, just change the message. The only difference is that it should be closed earlier than today (when the user signed the message, we close the modal)
- The call to connect the account already exists, it is on `src/app/routes/modals/RegisterModal/GithubSignin/index.tsx#43` with the function `connect`.

2022-10-11 14:26 UTC, J4ckyLIM commented on src/App/Routes/Modals/RegisterModal/GithubSignin/View.tsx
> +          <div>Estimated remaining time: 5 mins</div>
Oh yeah true

2022-10-11 14:28 UTC, ltoussaint approved these changes

2022-10-11 15:10 UTC, ltoussaint commented
@J4ckyLIM you have to rebase the `develop` branch into yours
Make sure to rebase from the upstream branch (the one from OnlyDust repo) as we had to perform a force push on develop few days ago

2022-10-11 15:58 UTC, closed without merging