E 1043 uniformise links style across product
onlydustxyz/marketplace-frontend pull request #1726
Opened 2024-01-26 08:39 UTC by NeoxAzrot

e-1043-uniformise-links-style-across-product

2024-01-26 16:18 UTC, alexbeno commented on components/ds/link/link.tsx
> +  const relProps = rel ? rel : isExternal ? "noopener noreferrer" : undefined;
`
const relExternal = isExternal ? "noopener noreferrer" : undefined;
const relProps = rel || relExternal;
`

2024-01-26 16:23 UTC, alexbeno requested changes

2024-01-26 16:23 UTC, alexbeno commented on components/ds/link/link.variants.ts
> +  base: "group/link inline-flex items-center gap-1 truncate hover:text-spacePurple-300",
you don't use `group/link` inside your code ?

2024-01-26 16:23 UTC, alexbeno commented on src/App/Stacks/ContributorProfileSidePanel/ReadOnlyView/IntroSection.tsx
> +            <Telegram size={24} />
why did you remove the className here ?

2024-01-26 16:23 UTC, alexbeno commented on src/App/Stacks/ContributorProfileSidePanel/ReadOnlyView/SocialLink.tsx
> +  const Component = link ? "a" : "button";
"div" was not used ?

2024-01-26 16:39 UTC, haydencleary commented on src/components/Project/Overview/OverviewSponsors.tsx
> +              </Typography>
You could store the rounded image in a variable to avoid repeating it

2024-01-26 16:39 UTC, haydencleary commented on src/components/Project/Overview/OverviewRepos/GithubRepoDetails/GithubLink/index.tsx
> +      <Button size="s" variant="secondary" iconOnly>
Not a fan of this, tried using the `as` prop ?

2024-01-26 16:39 UTC, haydencleary commented on src/components/Contributor/index.tsx
> +    <>
Don't need the fragment here if you return the ternary

2024-01-26 16:39 UTC, haydencleary commented on components/ds/link/link.tsx
> +  const isExternal = href?.toString().startsWith("http") ?? false;
I think this should be passed explicitly as a prop

2024-01-26 16:39 UTC, haydencleary commented on components/ds/link/link.tsx
> +  const relProps = rel ? rel : isExternal ? "noopener noreferrer" : undefined;
You could have a base `rel` value and extend it with the `isExternal` value and the `rel` prop. It would avoid nested ternaries

2024-01-26 16:39 UTC, haydencleary commented on components/ds/link/link.tsx
> +  const targetProps: HTMLAttributeAnchorTarget | undefined = target ? target : isExternal ? "_blank" : undefined;
Same as `rel`

2024-01-26 16:39 UTC, haydencleary commented on components/ds/link/link.tsx
> +    </>
It might be simpler to split these into separate components. In the case of an `onClick` I would use a `<button>` instead of a `<span>`

2024-01-29 08:49 UTC, NeoxAzrot commented on components/ds/link/link.tsx
> +  const relProps = rel ? rel : isExternal ? "noopener noreferrer" : undefined;
Rel use only if external, and if external use blank or take target

2024-01-29 08:54 UTC, NeoxAzrot commented on components/ds/link/link.tsx
> +    </>
Do 2 returns instead, with one return null

2024-01-29 08:56 UTC, NeoxAzrot commented on src/components/Project/Overview/OverviewSponsors.tsx
> +              </Typography>
Do a variable which return both

2024-01-29 09:19 UTC, NeoxAzrot commented on components/ds/link/link.variants.ts
> +  base: "group/link inline-flex items-center gap-1 truncate hover:text-spacePurple-300",
I do, with external

2024-01-29 09:20 UTC, NeoxAzrot commented on src/App/Stacks/ContributorProfileSidePanel/ReadOnlyView/IntroSection.tsx
> +            <Telegram size={24} />
It's done with currentColor now

2024-01-29 09:31 UTC, NeoxAzrot commented on src/App/Stacks/ContributorProfileSidePanel/ReadOnlyView/SocialLink.tsx
> +  const Component = link ? "a" : "button";
We want the component to be a button if there is an onClick action

2024-01-29 10:24 UTC, alexbeno approved these changes

2024-01-29 10:25 UTC, merged