WIP new create billing stack
onlydustxyz/marketplace-frontend pull request #1762
Opened 2024-02-02 13:33 UTC by alexbeno

2024-02-05 09:42 UTC, alexbeno commented
Blocked because of priority

2024-02-14 17:33 UTC, haydencleary requested changes

2024-02-14 17:33 UTC, haydencleary commented on components/ds/form/radio-group-custom/radio-group-custom.tsx
> +  return <>{childrenElements.map(child => child)}</>;
If the map returns the same element why is it necessary ?

2024-02-14 17:33 UTC, haydencleary commented on components/ds/form/radio-group-custom/radio-group-custom.tsx
> +    onChange(value as V);
Necessary to cast here ?

2024-02-14 17:33 UTC, haydencleary commented on components/ds/form/radio-group-custom/radio-group-custom.types.ts
> +    onChange: (value: string) => void;
Shouldn't this be :

```suggestion
    onChange: (value: V) => void;
```

2024-02-14 17:33 UTC, haydencleary commented on components/ds/form/radio-group/radio-group-item/radio-group-item.tsx
> +    () => children({ isSelected, isActive, isDisabled: disabled || false, value }),
Could give `disabled` a default value of `false` when destructured to avoid a condition here.

2024-02-14 17:33 UTC, haydencleary commented on components/ds/form/radio-group/radio-group.tsx
> +    onChange(value as V);
Same remark for cast

2024-02-14 17:33 UTC, haydencleary commented on components/features/stacks/billing-create-stack/billing-create-stack.tsx
> +                        <Translate key={3} token="v2.pages.settings.billing_create.fields.individual.points.3" />,
Why are there keys here ?

2024-02-14 17:33 UTC, haydencleary commented on components/features/stacks/billing-create-stack/billing-create-stack.tsx
> +                        <Translate key={2} token="v2.pages.settings.billing_create.fields.selfEmployed.points.2" />,
More keys

2024-02-14 17:33 UTC, haydencleary commented on components/features/stacks/billing-create-stack/billing-create-stack.tsx
> +                        <Translate key={3} token="v2.pages.settings.billing_create.fields.organisation.points.3" />,
And more keys

2024-02-14 17:33 UTC, haydencleary commented on components/features/stacks/billing-create-stack/billing-create-stack.tsx
> +                        <Translate key={2} token="v2.pages.settings.billing_create.fields.employee.points.2" />,
🗝️

2024-02-14 17:33 UTC, haydencleary commented on components/features/stacks/billing-create-stack/components/checkbox-item/checkbox-item.tsx
> +              <Typography variant={"title-s"} className="mb-[2px] text-greyscale-50">
```suggestion
              <Typography variant={"title-s"} className="mb-0.5 text-greyscale-50">
```

2024-02-14 17:33 UTC, haydencleary commented on src/translations/v2/en/pages/billing-create.json
> +        "2": "limited to 5,000 USD rewards per year",
```suggestion
        "2": "limited to 5,000 USD in rewards per year",
```

2024-02-21 14:52 UTC, alexbeno commented on components/ds/form/radio-group-custom/radio-group-custom.tsx
> +  return <>{childrenElements.map(child => child)}</>;
<img width="713" alt="Capture d’écran 2024-02-21 à 15 52 02" src="https://github.com/onlydustxyz/marketplace-frontend/assets/17259618/14106040-84bc-4b60-bbe4-155553770eec">

2024-02-21 14:56 UTC, alexbeno commented on components/ds/form/radio-group/radio-group.tsx
> +    onChange(value as V);
For this is an error from next ui value should be string for next UI but equal to V for us

2024-02-21 14:57 UTC, alexbeno commented on components/features/stacks/billing-create-stack/billing-create-stack.tsx
> +                        <Translate key={3} token="v2.pages.settings.billing_create.fields.individual.points.3" />,
![Uploading Capture d’écran 2024-02-21 à 15.56.59.png…]()

2024-02-21 14:58 UTC, alexbeno commented on components/features/stacks/billing-create-stack/billing-create-stack.tsx
> +                        <Translate key={3} token="v2.pages.settings.billing_create.fields.organisation.points.3" />,
Same

2024-02-21 14:58 UTC, alexbeno commented on components/features/stacks/billing-create-stack/billing-create-stack.tsx
> +                        <Translate key={2} token="v2.pages.settings.billing_create.fields.employee.points.2" />,
Same

2024-02-21 15:28 UTC, haydencleary approved these changes

2024-02-21 15:41 UTC, merged