feat/coworkers-invite-received
onlydustxyz/marketplace-frontend pull request #1938
Opened 2024-03-18 09:58 UTC by NeoxAzrot

feat/coworkers-invite-received

2024-03-18 17:30 UTC, haydencleary requested changes

2024-03-18 17:30 UTC, haydencleary commented on app/settings/components/form-footer/form-footer.tsx
> +        "absolute bottom-0 left-0 right-0 z-50 bg-spaceBlue-900 px-4 py-4 shadow-medium xl:px-8": isAbsolute,
```suggestion
        "absolute bottom-0 left-0 right-0 z-50 bg-spaceBlue-900 p-4 shadow-medium xl:px-8": isAbsolute,
```

2024-03-18 17:30 UTC, haydencleary commented on components/features/stacks/billing-create-stack/components/checkbox-item/checkbox-item.tsx
> +              />
Maybe `Checkbox` could be extracted into a variable ?

2024-03-18 17:30 UTC, haydencleary commented on translations/v2/en/pages/settings-billing/settings-billing-informations.json
> +    "description": "Please accept only if you are a member of this company.",
```suggestion
    "description": "Please only accept if you are a member of this company.",
```

2024-03-18 17:30 UTC, haydencleary commented on translations/v2/en/pages/settings-billing/settings-billing-informations.json
> +      "success": "You successfully joined __name__",
```suggestion
      "success": "You joined __name__ successfully",
```

2024-03-19 10:41 UTC, pixelfact commented on src/api/me/mutations.ts
> +    resourcePath: ME_PATH.BILLING_PROFILES_INVITATIONS(params?.billingProfileId || ""),
```suggestion
    resourcePath: ME_PATH.BILLING_PROFILES_INVITATIONS(params?.billingProfileId || ""),
    enabled: !!params?.billingProfileId,
```

2024-03-19 10:42 UTC, pixelfact approved these changes

2024-03-19 13:21 UTC, merged