Update currency model
onlydustxyz/marketplace-frontend pull request #1948
Opened 2024-03-19 14:17 UTC by alexbeno

2024-03-19 17:04 UTC, haydencleary requested changes

2024-03-19 17:04 UTC, haydencleary commented on src/components/Currency/CurrencyIcon.tsx
> -import Usdc from "src/assets/icons/Usdc";
Are these in use elsewhere ? If not you can remove them.

2024-03-19 17:04 UTC, haydencleary commented on src/components/Currency/CurrencyIcon.tsx
> +      className={cn("h-8 w-8 overflow-hidden rounded-full", className ? className : null)}
```suggestion
      className={cn("h-8 w-8 overflow-hidden rounded-full", className)}
```

2024-03-20 10:18 UTC, alexbeno commented on src/_pages/ProjectDetails/Rewards/Budget/Budget.tsx
> +import { Money as TMoney } from "src/types";
The naming is not good for Money it represent schema from backend, the naming should be Budget instead i don't know if we want to make this now ?

2024-03-20 10:21 UTC, alexbeno commented on src/_pages/ProjectDetails/Rewards/Budget/Panel.tsx
>                  {total === "N/A"
Argument of type number | "N/A" is not assignable to parameter of type number

2024-03-20 10:23 UTC, alexbeno commented on src/_pages/Rewards/Earning/Amount.tsx
> -  [Currency.USDC]: <Usdc className="h-4 w-4" />,
At the icons construction is not easy we could keep it in case of need when boostraping a features without dynamic currency

2024-03-20 10:38 UTC, haydencleary approved these changes

2024-03-20 10:38 UTC, haydencleary commented on utils/Money/Money.tsx
> +  private withTilde(str: string | number, prefixAmountWithTilde: boolean) {
Isn't the amount always a string here ?

```suggestion
  private withTilde(str: string, prefixAmountWithTilde: boolean) {
```

2024-03-20 10:43 UTC, merged