B 1537 build the technoecosystem accordion
onlydustxyz/marketplace-frontend pull request #2061
Opened 2024-04-29 12:52 UTC by pixelfact

2024-04-29 15:47 UTC, haydencleary requested changes

2024-04-29 15:47 UTC, haydencleary commented on components/ds/avatar/avatar.variants.ts
> +      size: "rectangleSize",
Not sure about these new values. The `shape` prop was designed to handle the radius of the avatar. Also, to me an avatar suggests that the width and height will be the same. Maybe your case should be a one-off ?

2024-04-29 15:47 UTC, haydencleary commented on app/migration/u/[githubLogin]/features/details-accordion/details-accordion.tsx
> +"use client";
Is it required to be a client component ? No hooks or events here

2024-04-29 16:22 UTC, pixelfact commented on app/migration/u/[githubLogin]/features/details-accordion/details-accordion.tsx
> +"use client";
Yes since the accordion from NextUi wrap in it some state handling ?! it was server at first then i got error...

2024-04-29 16:23 UTC, pixelfact commented on components/ds/avatar/avatar.variants.ts
> +      size: "rectangleSize",
yes I wasn't really sure if it could be considered an avatar variant. We discuss it live to find a better choice ?

2024-04-30 07:30 UTC, haydencleary requested changes

2024-04-30 07:30 UTC, haydencleary commented on components/ds/avatar/avatar.variants.ts
> +      rectangle: "",
I think you can remove this

2024-04-30 07:40 UTC, haydencleary approved these changes

2024-04-30 08:17 UTC, merged